name: Shannon Coder/Decoder CI Test

on: [push, pull_request]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y g++ make
        
    - name: Build project
      run: |
        make clean
        make
        
    - name: Create test files
      run: |
        echo -n "abracadabra" > input.txt  # -n чтобы избежать автоматического \n
        head -c 100 /dev/urandom > random.bin
        
    - name: Run text file test
      run: |
        ./coder input.txt encoded.bin dict.txt
        ./decoder encoded.bin decoded.txt dict.txt
        
        # Проверяем точное совпадение (включая отсутствие \n)
        cmp -b input.txt decoded.txt || (echo "Text file content mismatch!" && exit 1)
        [ $(stat -c%s input.txt) -eq $(stat -c%s decoded.txt) ] || (echo "File size mismatch!" && exit 1)
        echo "Text file test passed!"
        
    - name: Run binary file test
      run: |
        ./coder random.bin encoded.bin dict.txt
        ./decoder encoded.bin decoded.bin dict.txt
        
        cmp -b random.bin decoded.bin || (echo "Binary file test failed!" && exit 1)
        echo "Binary file test passed!"
        
